### ISSUE TITLE
import mappings to WhichKey

### ISSUE THREAD

**Issue by snowmang1** [snowmang1/nvim#78]
## tasks
- [ ] all mappings have desc or register with which key
- [ ] mappings.lua includes registry
- [ ] optimize lazy loading mappings
